// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo-qpaNs69Nt80WxjeCN3scNs21CZbmdg',
    appId: '1:385330072075:web:22849bb310fef0ea5e550e',
    messagingSenderId: '385330072075',
    projectId: 'flutter-wishlist-43a25',
    authDomain: 'flutter-wishlist-43a25.firebaseapp.com',
    storageBucket: 'flutter-wishlist-43a25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_43efsKA5MbOvxWDOpp6nDMX3ve_Wpk8',
    appId: '1:385330072075:android:797c704595b203bb5e550e',
    messagingSenderId: '385330072075',
    projectId: 'flutter-wishlist-43a25',
    storageBucket: 'flutter-wishlist-43a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnZ0KNErTVoqgWfAerJz98YfiwomlhWGk',
    appId: '1:385330072075:ios:058fd4009b9756b65e550e',
    messagingSenderId: '385330072075',
    projectId: 'flutter-wishlist-43a25',
    storageBucket: 'flutter-wishlist-43a25.firebasestorage.app',
    iosBundleId: 'com.example.appWishlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnZ0KNErTVoqgWfAerJz98YfiwomlhWGk',
    appId: '1:385330072075:ios:058fd4009b9756b65e550e',
    messagingSenderId: '385330072075',
    projectId: 'flutter-wishlist-43a25',
    storageBucket: 'flutter-wishlist-43a25.firebasestorage.app',
    iosBundleId: 'com.example.appWishlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo-qpaNs69Nt80WxjeCN3scNs21CZbmdg',
    appId: '1:385330072075:web:de7672ecef7964fa5e550e',
    messagingSenderId: '385330072075',
    projectId: 'flutter-wishlist-43a25',
    authDomain: 'flutter-wishlist-43a25.firebaseapp.com',
    storageBucket: 'flutter-wishlist-43a25.firebasestorage.app',
  );
}
